create table author
(
    id          bigint generated by default as identity
        primary key,
    name        varchar(255),
    surname     varchar(255),
    country     varchar(255),
    biography   varchar(255),
    book_ids    bigint references book on delete cascade
);

create table book
(
    id              bigint generated by default as identity
        primary key,
    title           varchar(255),
    genre           varchar(255),
    country         varchar(255),
    average_rating  double precision,
    author_id       bigint references author,
    genre_id        bigint references genre
);

create table genre
(
    id      bigint generated by default as identity
        primary key,
    name            varchar(255),
    description     varchar(255)
)